<a href="https://colab.research.google.com/github/davidgonzalez14/clase_de_econometria-/blob/main/Segundo_Taller.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install wooldridge
import numpy as np
import pandas as pd
import wooldridge as wd



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 57.3 MB/s eta 0:00:00


In [5]:
df=wd.data("wage1")


In [6]:
df= df [["exper", "educ", "wage"]]

In [7]:
df

exper  educ   wage
0        2    11   3.10
1       22    12   3.24
2        2    11   3.00
3       44     8   6.00
4        7    12   5.30
..     ...   ...    ...
521     14    16  15.00
522      2    10   2.27
523     13    15   4.67
524      5    16  11.56
525      5    14   3.50

[526 rows x 3 columns]

In [8]:
dfy=df[["wage"]]
dfy


wage
0     3.10
1     3.24
2     3.00
3     6.00
4     5.30
..     ...
521  15.00
522   2.27
523   4.67
524  11.56
525   3.50

[526 rows x 1 columns]

In [9]:
dfx=df[["exper","educ"]]
dfx

exper  educ
0        2    11
1       22    12
2        2    11
3       44     8
4        7    12
..     ...   ...
521     14    16
522      2    10
523     13    15
524      5    16
525      5    14

[526 rows x 2 columns]

In [10]:
arr = dfy.to_numpy()
print(arr)

[[ 3.0999999 ]
 [ 3.24000001]
 [ 3.        ]
 [ 6.        ]
 [ 5.30000019]
 [ 8.75      ]
 [11.25      ]
 [ 5.        ]
 [ 3.5999999 ]
 [18.18000031]
 [ 6.25      ]
 [ 8.13000011]
 [ 8.77000046]
 [ 5.5       ]
 [22.20000076]
 [17.32999992]
 [ 7.5       ]
 [10.63000011]
 [ 3.5999999 ]
 [ 4.5       ]
 [ 6.88000011]
 [ 8.47999954]
 [ 6.32999992]
 [ 0.52999997]
 [ 6.        ]
 [ 9.56000042]
 [ 7.78000021]
 [12.5       ]
 [12.5       ]
 [ 3.25      ]
 [13.        ]
 [ 4.5       ]
 [ 9.68000031]
 [ 5.        ]
 [ 4.67999983]
 [ 4.26999998]
 [ 6.1500001 ]
 [ 3.50999999]
 [ 3.        ]
 [ 6.25      ]
 [ 7.80999994]
 [10.        ]
 [ 4.5       ]
 [ 4.        ]
 [ 6.38000011]
 [13.69999981]
 [ 1.66999996]
 [ 2.93000007]
 [ 3.6500001 ]
 [ 2.9000001 ]
 [ 1.63      ]
 [ 8.60000038]
 [ 5.        ]
 [ 6.        ]
 [ 2.5       ]
 [ 3.25      ]
 [ 3.4000001 ]
 [10.        ]
 [21.62999916]
 [ 4.38000011]
 [11.71000004]
 [12.39000034]
 [ 6.25      ]
 [ 3.71000004]
 [ 7.78000021]
 [19.97999954]
 [ 6.25   

In [11]:
arr = dfx.to_numpy()
print(arr)

[[ 2 11]
 [22 12]
 [ 2 11]
 ...
 [13 15]
 [ 5 16]
 [ 5 14]]


In [12]:
arr2 = dfy.to_numpy()
print(arr2)

[[ 3.0999999 ]
 [ 3.24000001]
 [ 3.        ]
 [ 6.        ]
 [ 5.30000019]
 [ 8.75      ]
 [11.25      ]
 [ 5.        ]
 [ 3.5999999 ]
 [18.18000031]
 [ 6.25      ]
 [ 8.13000011]
 [ 8.77000046]
 [ 5.5       ]
 [22.20000076]
 [17.32999992]
 [ 7.5       ]
 [10.63000011]
 [ 3.5999999 ]
 [ 4.5       ]
 [ 6.88000011]
 [ 8.47999954]
 [ 6.32999992]
 [ 0.52999997]
 [ 6.        ]
 [ 9.56000042]
 [ 7.78000021]
 [12.5       ]
 [12.5       ]
 [ 3.25      ]
 [13.        ]
 [ 4.5       ]
 [ 9.68000031]
 [ 5.        ]
 [ 4.67999983]
 [ 4.26999998]
 [ 6.1500001 ]
 [ 3.50999999]
 [ 3.        ]
 [ 6.25      ]
 [ 7.80999994]
 [10.        ]
 [ 4.5       ]
 [ 4.        ]
 [ 6.38000011]
 [13.69999981]
 [ 1.66999996]
 [ 2.93000007]
 [ 3.6500001 ]
 [ 2.9000001 ]
 [ 1.63      ]
 [ 8.60000038]
 [ 5.        ]
 [ 6.        ]
 [ 2.5       ]
 [ 3.25      ]
 [ 3.4000001 ]
 [10.        ]
 [21.62999916]
 [ 4.38000011]
 [11.71000004]
 [12.39000034]
 [ 6.25      ]
 [ 3.71000004]
 [ 7.78000021]
 [19.97999954]
 [ 6.25   

In [13]:
X=np.c_[np.ones(len(dfx)),dfx]
X

array([[ 1.,  2., 11.],
       [ 1., 22., 12.],
       [ 1.,  2., 11.],
       ...,
       [ 1., 13., 15.],
       [ 1.,  5., 16.],
       [ 1.,  5., 14.]])

In [16]:
betas=np.linalg.inv(X.T.dot(X)).dot(X.T.dot(dfy))
betas.squeeze
betas



array([[-3.39053946],
       [ 0.0700954 ],
       [ 0.64427208]])

In [17]:
y_est=(X@betas)
y_est

array([[ 3.83664416],
       [ 5.88282415],
       [ 3.83664416],
       [ 4.84783456],
       [ 4.83139322],
       [ 7.54867231],
       [ 9.25778884],
       [ 4.69120242],
       [ 6.16320574],
       [ 9.10418453],
       [ 7.47857691],
       [ 5.19528371],
       [ 5.39215638],
       [ 5.60244257],
       [ 6.51368272],
       [ 7.89914929],
       [ 5.0416794 ],
       [ 6.10652385],
       [ 5.25196559],
       [ 6.8641597 ],
       [ 5.1117748 ],
       [ 6.37349193],
       [ 7.54867231],
       [ 4.55101163],
       [ 6.28998302],
       [ 7.12809993],
       [ 7.6888631 ],
       [ 9.09077102],
       [ 8.37640355],
       [ 2.39449571],
       [ 7.2414637 ],
       [ 5.76946039],
       [ 6.10652385],
       [ 4.83139322],
       [ 4.55101163],
       [ 8.45991246],
       [ 5.39215638],
       [ 1.92026928],
       [ 5.83955578],
       [ 5.1117748 ],
       [ 4.55101163],
       [ 5.74263336],
       [ 6.75079593],
       [ 6.85074619],
       [ 5.75604687],
       [ 7

In [18]:
u_est=arr2-y_est
u_est

array([[-7.36644256e-01],
       [-2.64282415e+00],
       [-8.36644160e-01],
       [ 1.15216544e+00],
       [ 4.68606975e-01],
       [ 1.20132769e+00],
       [ 1.99221116e+00],
       [ 3.08797577e-01],
       [-2.56320583e+00],
       [ 9.07581577e+00],
       [-1.22857691e+00],
       [ 2.93471641e+00],
       [ 3.37784407e+00],
       [-1.02442571e-01],
       [ 1.56863180e+01],
       [ 9.43085063e+00],
       [ 2.45832060e+00],
       [ 4.52347626e+00],
       [-1.65196569e+00],
       [-2.36415970e+00],
       [ 1.76822532e+00],
       [ 2.10650762e+00],
       [-1.21867239e+00],
       [-4.02101166e+00],
       [-2.89983019e-01],
       [ 2.43190049e+00],
       [ 9.11371087e-02],
       [ 3.40922898e+00],
       [ 4.12359645e+00],
       [ 8.55504295e-01],
       [ 5.75853630e+00],
       [-1.26946039e+00],
       [ 3.57347645e+00],
       [ 1.68606785e-01],
       [ 1.28988197e-01],
       [-4.18991248e+00],
       [ 7.57843712e-01],
       [ 1.58973071e+00],
       [-2.8

In [19]:
Var=(u_est.T.dot(u_est))/523
Var

array([[10.60833612]])

In [20]:
ee=np.diag(np.sqrt(Var*(np.linalg.inv(X.T.dot(X)))))
ee 

<ipython-input-20-f1ee05697a79>:1: RuntimeWarning: invalid value encountered in sqrt
  ee=np.diag(np.sqrt(Var*(np.linalg.inv(X.T.dot(X)))))


array([0.76656609, 0.01097764, 0.05380607])

In [21]:
est_t=betas/ee
est_t

array([[-4.42302300e+00, -3.08858821e+02, -6.30140685e+01],
       [ 9.14407727e-02,  6.38529107e+00,  1.30274139e+00],
       [ 8.40465135e-01,  5.86895141e+01,  1.19739661e+01]])